### ISSUE TITLE
Inappropriate tolerance for DC operating point setting resistors

### ISSUE THREAD

**Issue by jonnew** [open-ephys/oe-acquisition-board-gen3#23]
The use of 5% resistors when shifting the DC operating point for analog to digital conversion causes large DC errors.

![image](https://github.com/user-attachments/assets/6f3cc9db-afab-404f-9279-b4eded74e96e)

These should ideally match the absolute DC resolution of the reference, which is going to be ~1% given its own feedback resistor network tolerance.  Use 1% instead.

**Comment by filcarv** [comment]
The resistors were updated to 1% tolerance.
