### ISSUE TITLE
Analog switches to select MISO2 from BNO i2c or LVDS from second intan

### ISSUE THREAD

**Issue by aacuevas** [open-ephys/oe-acquisition-board-gen3#3]
These seem appropriate:
https://www.ti.com/product/TMUX136
https://www.ti.com/product/TMUX154E (in QFN packaging)

**Comment by filcarv** [comment]
We can hack one acquisition board to accommodate a preliminary schematic. This would help to validate these ICs.

**Comment by aacuevas** [comment]
Each channel would require 3 extra lines from the FPGA, 2 for I2C lines and a 3rd for selection between I2C and LVDS. We have 16 unused lines from the 2.5V bank of the FPGA that are currently routed to the breakout portion of the board (which we can get rid of). Those are the lines marked in red in this image
<img width="377" alt="oe-sch" src="https://github.com/open-ephys/oe-acquisition-board/assets/1830303/a9e93596-6ce4-49e3-9be8-bb067f2e6b2a">


Connection to the multiplexers is easy, one port of the multiplexers (either A or B, but the same for all 4 multiplexers) would go to the pins currently used for LVDS (MISO2), the other port would be used for I2C and the common port would be connected to the Omnetics header, where the current MISO2 lines are now
<img width="454" alt="ic-conns" src="https://github.com/open-ephys/oe-acquisition-board/assets/1830303/c10c56a9-7681-430f-b324-799a4d4dff1c">

Important points
- LVDS polarity must be respected, for example if A port is used for LVDS and COM1 is connected to MISO2+, then A1 must be connected to the P port (so basically, in LVDS mode, the circuit must be equivalent to what it is now, lines must not be swapped)
- TOTAL LVDS-MISO2 length (FPGA pins to mux+ mux to omnetics + equivalent length of mux) must be the same as MISO1 (FPGA to omnetics).

Equivalent length of the mux actually depends on the propagation delay of the lines on our PCB (what must actually match between MISO1 and 2 is the propagation delay), and to estimate that I'd need the stackup of the PCB and its dielectric Er. Propagation delay of the mux is 100ps. VERY rough estimation wit standard parameters (FR4), would be ~19mm equivalent length
( @jonnew please correct me if I'm wrong with having to use this equivalent length for MISO2 so it matches MISO1 )

**Comment by aacuevas** [comment]
Ok, ignore most of my last remarks. The IC delay is not significant enough

**Comment by filcarv** [comment]
We've made the following changes to an existing unit in order to validate the ICs.

![image](https://github.com/open-ephys/oe-acquisition-board/assets/34546039/aeb6cc68-c42f-4cf3-8a12-962fbc82cb88)
