### ISSUE TITLE
Replace aux ADC and DACs

### ISSUE THREAD

**Issue by jonnew** [open-ephys/oe-acquisition-board-gen3#4]
The ADCs and DACs are 16-bit, old devices:

- ADC: ADS8325IDGKT
- DAC: DAC8531E/250

The effective resolution of the aux IO is more like 10 bits given various noise sources on the board. Replace with a more cost effective alternative.

**Comment by jonnew** [comment]
Some more notes
- Currently, it looks like there are logic level converters to take 3.3V from the FPGA to 5V logic on these converters. This is clearly not great. Most modern chips will have logic thresholds that dont depend on the analog supply (e.g. 2.2V high).
- ADCs and DACs both run on 5V power but then use REF195 along with dedicated reference input for precision 5V reference. Given how noisy the circuit is, empirically, this is total overkill and we could use VDD-referred chips sans reference.
- Both ADC and DACs have analog front end that scales/shifts voltages into +/-5V. These circuits' passives could simply be changed so that 0-2.5V or 0-3.3V is scaled into +/-5 and then no logic level conversion is required (this point is in addition to the first).

**Comment by aacuevas** [comment]
We already do level shifting to translate 0-5 to -5 +5, so scaling 0-3.3 to -5 +5 would be mostly the same, indeed. We could probably use the same overall circuit, just some resistor adjustment.

**Comment by aacuevas** [comment]
Some time ago, @jonnew  proposed the following alternatives for ADC:

ADC122S021CIMM/NOPB
ADC121S021CIMFX/NOPB
BU79100G-LATR
ADC121S051

I propose using the ADC121S021 as it has the most similar characteristics and bus interface ad the current ones

**Comment by aacuevas** [comment]
DAC selection should have a "3-wire" interface (not I2C nor SPI) to easily connect them to the acquisition board HDL without big changes.

**Comment by jonnew** [comment]
For the DAC, this is what I've found:

### Original DAC
**Part:**  DAC8531E/250, $7.30 @ qty 100
**Features:**
- 16 bits (of which, ~4.5 are used by the board)
- Internal buffer's Vout and FB pin are exposed. However, they are tied together in the schematic so this is a unity gain buffer and we can use parts with unity gain buffers)
- 3-wire interface (~CS is used to frame data and load the DAC on its rising edge). 
- 24-bit frame format:   [X X X X X X PD1 PD2 D15 D14 ... D0]
  - X - Dont care
  - PDx - power down
  - Dx - data

### Alternatives
1. [MCP4921T-E/MS](https://ww1.microchip.com/downloads/en/DeviceDoc/22248a.pdf) , $1.97 @ qty 100
   - 12 bit instead of 16
   - Unity gain buffered by default
   - Same package as original , different pinout
   - Similar digital interface, but **Requires ~LDAC to load the DAC**.  Note that a single extra digital line could be used for the whole back to simultaneously update all DACS.
   - 16-bit frame format:   [X C1 C2 C3 D11 ... D0]
      - X - Dont care
      - Cx - control bits
      - Dx - data
  - **PCB and gateware will need changes** 
2. [TPC114S1-VR](https://static.3peak.com/res/doc/ds/Datasheet_TPC112S1-TPC114S1-TPC116S1.pdf) , $2.45 @ qty 100
   - 14 bits instead of 16
   - **Drop in replacement (hardware and gateware)** clearly a clone.
3. [DAC7513E/2K5](https://www.ti.com/lit/ds/symlink/dac7513.pdf?HQS=dis-dk-null-digikeymode-dsf-pf-null-wwe&ts=1725486852270&ref_url=https%253A%252F%252Fwww.ti.com%252Fgeneral%252Fdocs%252Fsuppproductinfo.tsp%253FdistId%253D10%2526gotoUrl%253Dhttps%253A%252F%252Fwww.ti.com%252Flit%252Fgpn%252Fdac7513) $2.87 @ qty 100
   - 12 bits
   - 16-bit frame format:   [X X PD1 PD2 D11 D14 ... D0]
      - X - Dont care
      - Cx - control bits
      - Dx - data
   - Same manufacturer and arch. as original, less resolution and different serail write length.
   - **Drop in replacement (hardware only)**

There are other options, but they are getting more expensive and don't cover anything that is not covered above, as far as I can tell.

**Comment by aacuevas** [comment]
For 1:

> The LDAC (... ) can be tied to low (VSS) if the VOUT update is desired at the rising edge of the CS pin. 

so we could not even use that line.

In order of fw changes, 1 requires the most nonetheless, then 3 and obviously, 2 would be a drop-in

However, I am wary of the long-term availability of 2. Microchip and TI are well-known brands, I haven't heard of 3-peak. 

So IMHO it's either 1 or 3. 1 will need a little bit more development and testing, 3 will need some, but less. Difference is 1€ per chip, which ends being non-trivial though.

**Comment by jonnew** [comment]
I second what Aaron is saying. We discussed today in our meeting and it seems that given the fact that hardware mods are happening on the board anyway, going with (1) the correct decision.
